/**
 * TipJar — app.js
 * Wallet connection, network guarding, tip sending,
 * and live on-chain supporter feed via eth_getLogs.
 *
 * Dependencies:
 *   - ethers v6 (loaded via CDN in index.html)
 *   - frontend/contract-address.json  (generated by deploy.js)
 *   - frontend/TipJarABI.json         (generated by deploy.js)
 */

/* ═══════════════════════════════════════════════════════════════════════════
   CONFIGURATION
   ═══════════════════════════════════════════════════════════════════════════ */

// Supported networks — extended at loadContractConfig() time
const NETWORKS = {
  sepolia: {
    chainId:      11155111n,
    chainIdHex:   "0xaa36a7",
    name:         "Sepolia Testnet",
    rpcUrl:       "https://ethereum-sepolia-rpc.publicnode.com",
    explorerBase: "https://sepolia.etherscan.io",
    params: {
      chainId:           "0xaa36a7",
      chainName:         "Sepolia Testnet",
      nativeCurrency:    { name: "Sepolia Ether", symbol: "ETH", decimals: 18 },
      rpcUrls:           ["https://ethereum-sepolia-rpc.publicnode.com"],
      blockExplorerUrls: ["https://sepolia.etherscan.io"],
    },
  },
  localhost: {
    chainId:      31337n,
    chainIdHex:   "0x7a69",
    name:         "Localhost 8545",
    rpcUrl:       "http://127.0.0.1:8545",
    explorerBase: null,   // no block explorer for local
    params: null,         // MetaMask already knows localhost
  },
};

// Active network — set by loadContractConfig() based on contract-address.json
let ACTIVE_NETWORK = NETWORKS.sepolia;

const MAX_MESSAGE_LENGTH = 280;
// Fetch events from this many blocks back on first load
const EVENT_LOOKBACK_BLOCKS_SEPOLIA  = 100_000;
const EVENT_LOOKBACK_BLOCKS_LOCALHOST = 9_999;  // local chain is short

/* ═══════════════════════════════════════════════════════════════════════════
   STATE
   ═══════════════════════════════════════════════════════════════════════════ */

let provider   = null;   // ethers.BrowserProvider
let signer     = null;   // ethers.Signer
let contract   = null;   // ethers.Contract (with signer for writes)
let roContract = null;   // read-only contract (no signer needed)
let roProvider = null;   // read-only provider for public RPC

let contractAddress = null;
let contractABI     = null;

let connectedAccount = null;
let tipListener      = null;   // real-time event listener

/* ═══════════════════════════════════════════════════════════════════════════
   DOM REFS
   ═══════════════════════════════════════════════════════════════════════════ */

const btnConnect         = document.getElementById("btn-connect");
const btnSendTip         = document.getElementById("btn-send-tip");
const btnSendIcon        = document.getElementById("btn-send-icon");
const btnSendText        = document.getElementById("btn-send-text");
const btnSwitchNetwork   = document.getElementById("btn-switch-network");
const networkBadge       = document.getElementById("network-badge");
const networkWarning     = document.getElementById("network-warning");
const tipForm            = document.getElementById("tip-form");
const inputAmount        = document.getElementById("input-amount");
const inputMessage       = document.getElementById("input-message");
const charCounter        = document.getElementById("char-counter");
const txStatus           = document.getElementById("tx-status");
const feed               = document.getElementById("feed");
const statTotalTips      = document.getElementById("stat-total-tips");
const statTotalEth       = document.getElementById("stat-total-eth");
const statSupporters     = document.getElementById("stat-supporters");
const contractAddrDisplay= document.getElementById("contract-address-display");
const etherscanLink      = document.getElementById("etherscan-link");
const footerEtherscan    = document.getElementById("footer-etherscan");
const toastContainer     = document.getElementById("toast-container");
const presetChips        = document.querySelectorAll(".preset-chip");

/* ═══════════════════════════════════════════════════════════════════════════
   UTILITIES
   ═══════════════════════════════════════════════════════════════════════════ */

/** Shorten 0xabc...xyz → 0xabc…xyz */
function shortAddr(addr) {
  if (!addr) return "";
  return addr.slice(0, 6) + "…" + addr.slice(-4);
}

/** Format wei → "0.0123 ETH" */
function fmtEth(wei) {
  const val = ethers.formatEther(wei);
  const num  = parseFloat(val);
  if (num === 0) return "0 ETH";
  if (num < 0.0001) return "<0.0001 ETH";
  return num.toPrecision(4).replace(/\.?0+$/, "") + " ETH";
}

/** Relative time: "2 min ago", "just now", etc. */
function relativeTime(timestamp) {
  const ts  = typeof timestamp === "bigint" ? Number(timestamp) : timestamp;
  const sec = Math.floor(Date.now() / 1000) - ts;
  if (sec < 10)  return "just now";
  if (sec < 60)  return `${sec}s ago`;
  if (sec < 3600)return `${Math.floor(sec/60)}m ago`;
  if (sec < 86400)return `${Math.floor(sec/3600)}h ago`;
  return `${Math.floor(sec/86400)}d ago`;
}

/** Deterministic color from an address */
function addrColor(addr) {
  let h = 0;
  for (let i = 2; i < 8; i++) h = (h * 16 + parseInt(addr[i], 16)) % 360;
  return `hsl(${h}, 60%, 55%)`;
}

/** First non-zero hex char of address → avatar letter */
function addrInitial(addr) {
  return addr ? addr.slice(2, 3).toUpperCase() : "?";
}

/* ═══════════════════════════════════════════════════════════════════════════
   TOAST NOTIFICATIONS
   ═══════════════════════════════════════════════════════════════════════════ */

function showToast(message, type = "info", duration = 4000) {
  const icons = { success: "✅", error: "❌", info: "ℹ️", warning: "⚠️" };
  const toast = document.createElement("div");
  toast.className = `toast toast--${type}`;
  toast.setAttribute("role", "alert");
  toast.innerHTML = `<span>${icons[type] || "ℹ️"}</span><span>${message}</span>`;
  toastContainer.appendChild(toast);
  setTimeout(() => toast.remove(), duration + 300);
}

/* ═══════════════════════════════════════════════════════════════════════════
   TRANSACTION STATUS BAR
   ═══════════════════════════════════════════════════════════════════════════ */

function setTxStatus(html, visible = true) {
  txStatus.innerHTML = html;
  txStatus.classList.toggle("visible", visible);
}

function clearTxStatus() { setTxStatus("", false); }

/* ═══════════════════════════════════════════════════════════════════════════
   NETWORK GUARD
   ═══════════════════════════════════════════════════════════════════════════ */

async function checkNetwork() {
  if (!provider) return false;
  const network = await provider.getNetwork();
  const onRight = network.chainId === ACTIVE_NETWORK.chainId;

  networkWarning.classList.toggle("visible", !onRight);

  if (onRight) {
    networkBadge.textContent   = ACTIVE_NETWORK.name;
    networkBadge.className     = "network-badge";
    networkBadge.style.display = "inline-flex";
    btnSendTip.disabled = false;
    updateButtonState("ready");
  } else {
    networkBadge.textContent   = "Wrong Network";
    networkBadge.className     = "network-badge network-badge--wrong";
    networkBadge.style.display = "inline-flex";
    btnSendTip.disabled = true;
    updateButtonState("wrong-network");
  }

  return onRight;
}

async function switchToActiveNetwork() {
  if (!window.ethereum) return;
  try {
    await window.ethereum.request({
      method: "wallet_switchEthereumChain",
      params: [{ chainId: ACTIVE_NETWORK.chainIdHex }],
    });
  } catch (err) {
    // 4902 = chain not added yet in MetaMask
    if (err.code === 4902 && ACTIVE_NETWORK.params) {
      try {
        await window.ethereum.request({
          method: "wallet_addEthereumChain",
          params: [ACTIVE_NETWORK.params],
        });
      } catch (addErr) {
        showToast(`Could not add ${ACTIVE_NETWORK.name}.`, "error");
      }
    } else {
      showToast("Network switch cancelled.", "warning");
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   BUTTON STATE MANAGEMENT
   ═══════════════════════════════════════════════════════════════════════════ */

function updateButtonState(state) {
  const states = {
    "no-wallet":     { icon: "🦊", text: "Install MetaMask",     disabled: true  },
    "disconnected":  { icon: "🔗", text: "Connect Wallet First", disabled: true  },
    "wrong-network": { icon: "⚠️", text: "Switch to Sepolia",    disabled: true  },
    "ready":         { icon: "☕", text: "Send Tip",              disabled: false },
    "pending":       { icon: "",   text: "Pending…",             disabled: true  },
    "success":       { icon: "✅", text: "Tip Sent!",            disabled: false },
  };

  const s = states[state] || states["disconnected"];
  btnSendIcon.textContent = s.icon;
  btnSendText.textContent = s.text;
  btnSendTip.disabled = s.disabled;

  btnSendTip.classList.toggle("pending", state === "pending");

  if (state === "pending") {
    const spinner = document.createElement("div");
    spinner.className = "spinner";
    spinner.id = "send-spinner";
    btnSendIcon.replaceWith(spinner);
  } else {
    const spinner = document.getElementById("send-spinner");
    if (spinner) spinner.replaceWith(btnSendIcon);
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   WALLET CONNECTION
   ═══════════════════════════════════════════════════════════════════════════ */

async function connectWallet() {
  if (!window.ethereum) {
    showToast("MetaMask not detected. Please install it.", "error");
    window.open("https://metamask.io/download/", "_blank");
    return;
  }

  try {
    provider = new ethers.BrowserProvider(window.ethereum);
    await provider.send("eth_requestAccounts", []);
    signer   = await provider.getSigner();
    connectedAccount = await signer.getAddress();

    // Bind contract with signer (for writes)
    contract = new ethers.Contract(contractAddress, contractABI, signer);

    // Update UI
    btnConnect.classList.add("wallet-pill--connected");
    btnConnect.innerHTML = `<span class="wallet-dot"></span>${shortAddr(connectedAccount)}`;
    btnConnect.setAttribute("aria-label", `Connected: ${connectedAccount}`);

    showToast(`Connected: ${shortAddr(connectedAccount)}`, "success");

    const onRight = await checkNetwork();
    if (onRight) {
      updateButtonState("ready");
      loadStats();
    }

    // Listen for account / chain changes
    window.ethereum.on("accountsChanged", handleAccountsChanged);
    window.ethereum.on("chainChanged",    handleChainChanged);

    // Start listening for live tips
    startLiveFeed();

  } catch (err) {
    if (err.code === 4001) {
      showToast("Connection rejected.", "warning");
    } else {
      showToast("Failed to connect wallet.", "error");
      console.error(err);
    }
  }
}

function handleAccountsChanged(accounts) {
  if (accounts.length === 0) {
    // Disconnected
    connectedAccount = null;
    signer   = null;
    contract = null;
    btnConnect.classList.remove("wallet-pill--connected");
    btnConnect.innerHTML = "Connect Wallet";
    updateButtonState("disconnected");
    networkBadge.style.display = "none";
    networkWarning.classList.remove("visible");
    stopLiveFeed();
    showToast("Wallet disconnected.", "info");
  } else {
    window.location.reload();
  }
}

function handleChainChanged() {
  window.location.reload();
}

/* ═══════════════════════════════════════════════════════════════════════════
   SEND TIP
   ═══════════════════════════════════════════════════════════════════════════ */

async function sendTip(amountEth, message) {
  updateButtonState("pending");
  clearTxStatus();

  try {
    const value = ethers.parseEther(amountEth);
    const tx    = await contract.tip(message, { value });

    setTxStatus(
      `<div class="spinner" style="border-color:rgba(22,24,87,0.3);border-top-color:var(--color-primary);"></div>
       <span>Transaction pending…&nbsp;
         <a href="https://sepolia.etherscan.io/tx/${tx.hash}" target="_blank" rel="noopener noreferrer">
           View on Etherscan ↗
         </a>
       </span>`
    );

    showToast("Transaction submitted, waiting for confirmation…", "info", 6000);

    const receipt = await tx.wait();

    if (receipt.status === 1) {
      updateButtonState("success");
      showToast("Tip confirmed! 🎉 You're on the wall!", "success");
      setTxStatus(
        `✅ Confirmed in block ${receipt.blockNumber.toLocaleString()}&nbsp;·&nbsp;
         <a href="https://sepolia.etherscan.io/tx/${tx.hash}" target="_blank" rel="noopener noreferrer">
           Etherscan ↗
         </a>`
      );

      // Reset form
      inputAmount.value  = "";
      inputMessage.value = "";
      updateCharCounter();

      // Refresh stats (the live feed picks up the event automatically)
      loadStats();

      setTimeout(() => { updateButtonState("ready"); clearTxStatus(); }, 5000);
    } else {
      throw new Error("Transaction reverted");
    }

  } catch (err) {
    console.error(err);
    updateButtonState("ready");

    // Classify error
    if (err.code === 4001 || err.code === "ACTION_REJECTED") {
      showToast("Transaction cancelled.", "warning");
      clearTxStatus();
    } else if (err.message?.includes("ZeroTip")) {
      showToast("Tip amount must be greater than 0.", "error");
    } else if (err.message?.includes("MessageTooLong")) {
      showToast("Message exceeds 280 characters.", "error");
    } else if (err.message?.includes("insufficient funds")) {
      showToast("Insufficient ETH in your wallet.", "error");
    } else {
      showToast("Transaction failed. Check console for details.", "error");
      setTxStatus(`❌ Transaction failed — <a href="https://sepolia.etherscan.io" target="_blank" rel="noopener noreferrer">check Etherscan</a>`);
    }
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   FORM HANDLING
   ═══════════════════════════════════════════════════════════════════════════ */

function updateCharCounter() {
  const len = inputMessage.value.length;
  charCounter.textContent = `${len} / ${MAX_MESSAGE_LENGTH}`;
  charCounter.className   = "char-counter";
  if (len >= MAX_MESSAGE_LENGTH)   charCounter.classList.add("at-limit");
  else if (len >= MAX_MESSAGE_LENGTH * 0.85) charCounter.classList.add("near-limit");
}

inputMessage.addEventListener("input", updateCharCounter);

// Preset chips
presetChips.forEach(chip => {
  chip.addEventListener("click", () => {
    inputAmount.value = chip.dataset.amount;
    inputAmount.focus();
  });
});

// Form submit
tipForm.addEventListener("submit", async (e) => {
  e.preventDefault();

  if (!contract) {
    showToast("Please connect your wallet first.", "warning");
    return;
  }

  const amountStr = inputAmount.value.trim();
  const message   = inputMessage.value.trim();

  // Validate amount
  if (!amountStr || parseFloat(amountStr) <= 0) {
    showToast("Please enter a tip amount greater than 0.", "warning");
    inputAmount.focus();
    return;
  }

  // Validate message length
  if (message.length > MAX_MESSAGE_LENGTH) {
    showToast(`Message too long (max ${MAX_MESSAGE_LENGTH} chars).`, "error");
    return;
  }

  const onRight = await checkNetwork();
  if (!onRight) {
    showToast("Switch to Sepolia testnet first.", "warning");
    return;
  }

  await sendTip(amountStr, message);
});

/* ═══════════════════════════════════════════════════════════════════════════
   STATS
   ═══════════════════════════════════════════════════════════════════════════ */

async function loadStats() {
  try {
    const src = roContract || contract;
    if (!src) return;

    const [tips, amount] = await Promise.all([
      src.totalTips(),
      src.totalAmount(),
    ]);

    statTotalTips.textContent  = tips.toLocaleString();
    statTotalEth.textContent   = fmtEth(amount);
    // Unique supporters = unique senders (approximated from feed)
    // Actual unique count computed when feed loads
  } catch (err) {
    console.warn("loadStats:", err);
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   SUPPORTER FEED — eth_getLogs / queryFilter
   ═══════════════════════════════════════════════════════════════════════════ */

function buildTipItem(log, isNew = false) {
  const { sender, amount, message, timestamp } = log.args;

  const item = document.createElement("article");
  item.className = "tip-item" + (isNew ? " tip-item--new" : "");
  item.setAttribute("role", "article");

  const color   = addrColor(sender);
  const initial = addrInitial(sender);
  const hasMsg  = message && message.trim().length > 0;

  item.innerHTML = `
    <div class="tip-item__avatar" style="background:linear-gradient(135deg,${color}99,${color})">
      ${initial}
    </div>
    <div class="tip-item__body">
      <div class="tip-item__row1">
        <span class="tip-item__address" title="${sender}">${shortAddr(sender)}</span>
        <span class="tip-item__amount">${fmtEth(amount)}</span>
      </div>
      <div class="tip-item__message${hasMsg ? "" : " tip-item__message--empty"}">
        ${hasMsg
          ? escapeHtml(message)
          : "<em>No message</em>"
        }
      </div>
      <div class="tip-item__time">${relativeTime(timestamp)}</div>
    </div>
  `;

  return item;
}

function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function renderSkeletons(count = 3) {
  feed.innerHTML = "";
  for (let i = 0; i < count; i++) {
    feed.innerHTML += `
      <div class="skeleton-row">
        <div class="skeleton skeleton-avatar"></div>
        <div class="skeleton-body">
          <div class="skeleton skeleton-line skeleton-line--short"></div>
          <div class="skeleton skeleton-line skeleton-line--long"></div>
        </div>
      </div>
    `;
  }
}

function renderEmpty() {
  feed.innerHTML = `
    <div class="feed-empty">
      <div class="feed-empty__icon">☕</div>
      <div class="feed-empty__text">No tips yet — be the first supporter!</div>
    </div>
  `;
}

async function loadHistoricalFeed() {
  const src = roContract || contract;
  if (!src) { renderEmpty(); return; }

  renderSkeletons();

  try {
    const roProv = roProvider || provider;
    const currentBlock = await roProv.getBlockNumber();
    const lookback = ACTIVE_NETWORK.chainId === 31337n
      ? EVENT_LOOKBACK_BLOCKS_LOCALHOST
      : EVENT_LOOKBACK_BLOCKS_SEPOLIA;
    const fromBlock = Math.max(0, currentBlock - lookback);

    const logs = await src.queryFilter(src.filters.NewTip(), fromBlock, "latest");

    if (logs.length === 0) { renderEmpty(); updateUniqueCount([]); return; }

    // Sort newest-first
    const sorted = [...logs].sort((a, b) =>
      Number(b.args.timestamp) - Number(a.args.timestamp)
    );

    feed.innerHTML = "";
    sorted.forEach(log => feed.appendChild(buildTipItem(log, false)));

    updateUniqueCount(sorted.map(l => l.args.sender));
    loadStats();

  } catch (err) {
    console.error("loadHistoricalFeed:", err);
    renderEmpty();
  }
}

function updateUniqueCount(senders) {
  const unique = new Set(senders.map(a => a.toLowerCase())).size;
  statSupporters.textContent = unique.toLocaleString();
}

function startLiveFeed() {
  const src = roContract || contract;
  if (!src || tipListener) return;

  tipListener = (sender, amount, message, timestamp) => {
    const log = { args: { sender, amount, message, timestamp } };
    const item = buildTipItem(log, true);

    if (feed.querySelector(".feed-empty")) {
      feed.innerHTML = "";
    }

    feed.insertBefore(item, feed.firstChild);
    // Debounced stats refresh
    loadStats();
  };

  src.on("NewTip", tipListener);
}

function stopLiveFeed() {
  if (contract && tipListener) {
    contract.off("NewTip", tipListener);
    tipListener = null;
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   CONTRACT CONFIG LOADER
   ═══════════════════════════════════════════════════════════════════════════ */

async function loadContractConfig() {
  try {
    // Load address + network
    const addrResp = await fetch("contract-address.json");
    if (!addrResp.ok) throw new Error("contract-address.json not found");
    const addrData  = await addrResp.json();
    contractAddress = addrData.address;

    // Set active network from deploy output
    const networkName = addrData.network || "sepolia";
    ACTIVE_NETWORK = NETWORKS[networkName] || NETWORKS.sepolia;

    // Load ABI
    const abiResp = await fetch("TipJarABI.json");
    if (!abiResp.ok) throw new Error("TipJarABI.json not found");
    contractABI = await abiResp.json();

    // Update contract-related UI
    contractAddrDisplay.textContent = contractAddress;

    // Update the network warning span
    const expectedNetEl = document.getElementById("expected-network");
    if (expectedNetEl) expectedNetEl.textContent = ACTIVE_NETWORK.name;

    const explorerUrl = ACTIVE_NETWORK.explorerBase
      ? `${ACTIVE_NETWORK.explorerBase}/address/${contractAddress}`
      : null;

    if (explorerUrl) {
      etherscanLink.href   = explorerUrl;
      footerEtherscan.href = explorerUrl;
      etherscanLink.textContent   = "View on Etherscan ↗";
      footerEtherscan.textContent = "Sepolia Etherscan";
    } else {
      etherscanLink.textContent   = "Local network (no explorer)";
      footerEtherscan.textContent = "Local network";
    }

    // Show which network the frontend is targeting
    const networkBannerEl = document.getElementById("network-banner-text");
    if (networkBannerEl) {
      networkBannerEl.textContent = `Running on ${ACTIVE_NETWORK.name}`;
    }

    // Read-only provider (RPC) for loading feed without wallet
    roProvider = new ethers.JsonRpcProvider(ACTIVE_NETWORK.rpcUrl);
    roContract = new ethers.Contract(contractAddress, contractABI, roProvider);

    return true;
  } catch (err) {
    console.warn("Contract config not deployed yet:", err.message);
    contractAddrDisplay.innerHTML =
      '<em style="color:#9ca3af">Not deployed — run: npm run deploy:localhost</em>';
    return false;
  }
}

/* ═══════════════════════════════════════════════════════════════════════════
   BOOTSTRAP
   ═══════════════════════════════════════════════════════════════════════════ */

async function init() {
  // 1. Load contract config (address + ABI from deploy output)
  const configured = await loadContractConfig();

  // 2. Load historical feed (works without wallet via public RPC)
  if (configured) {
    await loadHistoricalFeed();
    await loadStats();
  } else {
    renderEmpty();
  }

  // 3. Check if MetaMask available
  if (!window.ethereum) {
    updateButtonState("no-wallet");
    return;
  }

  updateButtonState("disconnected");

  // 4. Restore session if already connected
  try {
    const accounts = await window.ethereum.request({ method: "eth_accounts" });
    if (accounts.length > 0) {
      // Auto-reconnect without prompting
      await connectWallet();
    }
  } catch {
    // Not connected yet — user must click
  }

  // 5. Bind events
  btnConnect.addEventListener("click", connectWallet);
  btnSwitchNetwork.addEventListener("click", switchToActiveNetwork);
}

// Kick off
init().catch(console.error);
